spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.71/Sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    database: mysql
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell


logging:
  level: